services:
  # Serviço para o banco de dados PostgreSQL
  musiki-db:
    image: postgres:14
    ports:
      - "5433:${DB_PORT}"  # Mapeando a porta do PostgreSQL (5433 no host para 5432 no container)
    environment:
      POSTGRES_DB: ${DB_NAME}  # Usando a variável DB_NAME do .env
      POSTGRES_USER: ${DB_USER}  # Usando a variável DB_USER do .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # Usando a variável DB_PASSWORD do .env
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistência dos dados do banco
    networks:
      - musiki-network

  # Serviço para o backend (Spring Boot)
  spring-app:
    build:
      context: ./musikiAPI
      dockerfile: Dockerfile
    image: musiki-app:latest
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://musiki-db:${DB_PORT}/${DB_NAME} # Usando as variáveis do .env
      SPRING_DATASOURCE_USERNAME: ${DB_USER}  # Usando a variável DB_USER do .env
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}  # Usando a variável DB_PASSWORD do .env
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}  # Usando a variável do .env
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}  # Usando a variável do .env
      SERVER_PORT: ${SERVER_PORT}  # Carregar a variável do .env
    depends_on:
      - musiki-db
    networks:
      - musiki-network

  # Serviço para o frontend (React)
  spa-app:
    build:
      context: ./musikiprimefaces
      dockerfile: Dockerfile
    image: musiki-primefaces:latest
    ports:
      - "80:5000"
    env_file:
      - .env   # Caminho para o arquivo .env que está fora da pasta do seu projeto
    environment:
      #NODE_ENV: production
      #REACT_APP_API_URL: ${REACT_APP_API_URL}
      #REACT_APP_PORTA: ${REACT_APP_PORTA}
    depends_on:
      - spring-app
    networks:
      - musiki-network

# Definição da rede global (fora do bloco services)
networks:
  musiki-network:
    driver: bridge

# Definição dos volumes
volumes:
  postgres-data:
    driver: local