
services:
  musiki-db:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: musiki
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345

  spring-app:
    build:
      context: ./musikiAPI  # Caminho para o diretório onde está o Dockerfile
      dockerfile: Dockerfile  # Certifique-se de que o Dockerfile está nesse diretório
    image: musiki:latest  # Nome da imagem, se você quiser que ela seja 'latest'
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://musiki-db:5432/musiki
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - musiki-db

  spa-app:
    build:
      context: ./musikiprimefaces
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - spring-app
